
name: Build & Deploy


on:
  push:
    branches: [ nw_tests ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x' 

      - name: Build cargo-not
        run: |
          cd ./cargo-not/
          chmod a+rwx py/index.py
          vi +':wq ++ff=unix' py/index.py
          make closure
          make release
          rm .gitignore
      
      - name: Deploy Webpage
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
